CREATE TABLE "HR"."PRODUCT3" 
   (	"NO" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )
   
   
INSERT INTO "MEMBER" VALUES ('park','1234','park', '011')

INSERT INTO "MEMBER" VALUES ('apple','1111','apple', '011')

INSERT INTO "MEMBER" VALUES ('ice','2222','ice', '012')

INSERT INTO "MEMBER" VALUES ('melon','3333','melon', '013')

SELECT * FROM "MEMBER"

SELECT ID FROM "MEMBER"

SELECT ID, PW FROM "MEMBER"