CREATE TABLE HR."DEPT"
(
	DEPTNO NUMBER(2),
	DNAME VARCHAR2(14 BYTE),
	LOC VARCHAR2(13 BYTE)
)

CREATE TABLE HR."EMP"
(
	EMPNO NUMBER(4),
	ENAME VARCHAR2(10 BYTE),
	JOB VARCHAR2(9 BYTE),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7,2),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2)
)

CREATE TABLE HR."SALGRADE"
(
	GRADE NUMBER,
	LOSAL NUMBER,
	HISAL NUMBER
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY (DEPTNO));

ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY(EMPNO));

ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO));

SELECT * FROM EMP

SELECT DEPTNO FROM EMP

SELECT DISTINCT  DEPTNO FROM EMP

SELECT ENAME, SAL * 12 AS YEARSAL FROM EMP

SELECT * FROM EMP
ORDER BY SAL DESC

SELECT * FROM EMP
WHERE NOT DEPTNO = 30
ORDER BY EMPNO DESC

SELECT * FROM emp
WHERE DEPTNO = 30 AND JOB = 'salesman'

SELECT * FROM emp
WHERE DEPTNO = 30 or JOB = 'SALESMAN'

SELECT * FROM emp
WHERE sal >= 3000

SELECT * FROM emp
WHERE sal != 3000 

SELECT * FROM emp
WHERE job IN ('SALESMAN', 'MANAGER')
ORDER BY job

SELECT * FROM emp
WHERE job not IN ('SALESMAN', 'MANAGER')
ORDER BY job

SELECT * FROM emp
WHERE sal BETWEEN 2000 AND 3000 
ORDER BY empno

SELECT * FROM emp
WHERE sal NOT BETWEEN 2000 AND 3000 
ORDER BY empno

SELECT * FROM emp
WHERE ENAME LIKE '_L%'

SELECT * FROM emp
WHERE ENAME NOT LIKE '_L%'

SELECT * FROM emp
WHERE COMM IS NULL

SELECT * FROM emp
WHERE COMM IS NOT NULL

CREATE TABLE dept_temp2 
AS
SELECT * FROM DEPT

SELECT * FROM dept_temp2

UPDATE DEPT_TEMP2 
SET LOC = 'SEOUL'

UPDATE DEPT_TEMP2 
SET DNAME = 'DATABASE', loc = 'BUSAN'
WHERE DEPTNO = 40

DELETE FROM DEPT_TEMP2 
WHERE DNAME = 'SALES'

SELECT * FROM DEPT_TEMP2 dt