SELECT *
FROM PRODUCT3 P, COMPANY C
WHERE P.COMPANY  = C.ID

SELECT *
FROM PRODUCT3 P
LEFT OUTER JOIN COMPANY C
ON(P.COMPANY  = C.ID)

SELECT *
FROM PRODUCT3 P
RIGHT OUTER JOIN COMPANY C
ON(P.COMPANY  = C.ID)