CREATE TABLE "HR"."BBS2" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 

CREATE TABLE "HR"."BBS3" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
)

--PK제약조건 추가
ALTER TABLE HR.BBS3
ADD CONSTRAINT BBS3_PK PRIMARY KEY ("no")

--KF제약조건 추가
ALTER TABLE HR.BBS3
ADD CONSTRAINT FK_MEMBER3 FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);


CREATE TABLE HR."MEMBER" (
	ID VARCHAR2(100) NULL,
	PW VARCHAR2(100) NULL,
	NAME VARCHAR2(100) NULL,
	TEL VARCHAR2(100) NULL
)

--테이블 복사
CREATE  TABLE MEMBER22
AS SELECT * FROM MEMBER

INSERT INTO MEMBER22 
VALUES ('BANANA','BANANA','BANANA','BANANA', SYSDATE)

SELECT * FROM MEMBER22

INSERT INTO MEMBER22 
VALUES ('BANANA2','BANANA2','BANANA2','BANANA2', SYSDATE, 'GOOGLE')

SELECT * FROM MEMBER22

INSERT INTO BBS3
VALUES (BBS3_ID_SEQ.NEXTVAL, 'HAPPY', 'HAPPY DAY', 'ICE')

SELECT * FROM BBS3

CREATE SEQUENCE PD_ID_SEQ
INCREMENT BY 1
START WITH 1

CREATE TABLE PRODUCT2(
	ID NUMBER(38,0),
	NAME VARCHAR2(100)
)

INSERT INTO PRODUCT2 
VALUES (PD_ID_SEQ.NEXTVAL, 'SHOES')



CREATE SEQUENCE OR_ID_SEQ
INCREMENT BY 1
START WITH 1

CREATE TABLE ORDERLIST(
	ID NUMBER(38,0),
	TITLE VARCHAR2(100),
	PRICE NUMBER(38,0)
)

INSERT INTO ORDERLIST
VALUES (OR_ID_SEQ.NEXTVAL, 'SHOES', '10000')

SELECT * FROM ORDERLIST

SELECT * FROM ORDERLIST
ORDER BY ID -- 오름차순

SELECT * FROM ORDERLIST
ORDER BY ID DESC -- 내림차순



