CREATE TABLE PRODUCT3
(	"ID" VARCHAR2(200),
	"NAME" VARCHAR2(200),
	"CONTENT" VARCHAR2(200),
	"PRICE" NUMBER(38,0),
	"COMPANY" VARCHAR2(200),
	"IMG" VARCHAR2(200)
)

-- 2.
SELECT * FROM PRODUCT3
ORDER BY PRICE DESC

-- 3.
SELECT * FROM PRODUCT3
ORDER BY COMPANY

-- 4.
SELECT DISTINCT COMPANY FROM PRODUCT3

-- 5.
SELECT NAME, PRICE*5 AS PRICE5 FROM PRODUCT3

-- 6.
SELECT * FROM PRODUCT3
WHERE PRICE = 5000

-- 7.
SELECT * FROM PRODUCT3 
WHERE PRICE BETWEEN 3000 AND 6000

-- 8.
SELECT * FROM PRODUCT3
WHERE NOT COMPANY = 'c100'

-- 9.
SELECT * FROM PRODUCT3
WHERE COMPANY = 'c100' OR COMPANY = 'c200'

-- 10.
