CREATE TABLE STUDENT_INFORMATION
(
	학생번호 NUMBER(38,0),
	학생이름 VARCHAR2(20),
	주소 VARCHAR2(20),
	학과 VARCHAR2(20)
)

CREATE TABLE RECORD
(
	학생번호 NUMBER(38,0),
	강좌이름 VARCHAR2(20),
	성적 VARCHAR2(20)
)

CREATE TABLE SUBJECT
(
	강좌이름 VARCHAR2(20),
	강의실 VARCHAR2(20)
)

CREATE TABLE DEPARTMENT
(
	학과 VARCHAR2(20),
	학과사무실 VARCHAR2(20)
)

SELECT * FROM STUDENT_INFORMATION WHERE 학생번호
IN(SELECT 학생번호 FROM RECORD WHERE 성적 = 3.5)

SELECT * FROM RECORD
WHERE 강좌이름 = (SELECT 강좌이름 FROM SUBJECT WHERE 강의실 = '공학관110')

SELECT 학생번호 FROM RECORD
INNER JOIN SUBJECT ON
RECORD.강좌이름 = SUBJECT.강좌이름
AND 강의실 = '공학관110'

SELECT * FROM STUDENT_INFORMATION LEFT JOIN "RECORD" ON
STUDENT_INFORMATION.학생번호 = RECORD.학생번호 LEFT JOIN DEPARTMENT ON
STUDENT_INFORMATION.학과 = DEPARTMENT.학과 LEFT JOIN SUBJECT ON
RECORD.강좌이름 = SUBJECT.강좌이름

INSERT INTO STUDENT_INFORMATION VALUES(403, '박세리', '대전', '체육학과')

SELECT * FROM STUDENT_INFORMATION 



-- 네이버웹툰 -> 웹툰 -> 웹툰선정 -> 각 웹툰의 요일 장르 별점 3가지

CREATE TABLE WEBTOON_DAY
(
	연재일 VARCHAR2(20),
	작품 VARCHAR2(20),
	작가 VARCHAR2(20)
)

CREATE TABLE WEBTOON_TITLE
(
	제목 VARCHAR2(20),
	회차 VARCHAR2(20)
)

CREATE TABLE WEBTOON
(
	회차 VARCHAR2(20),
	회차정보 VARCHAR2(20),
	평점 NUMBER(38,0)
)

INSERT INTO WEBTOON_DAY VALUES ('월요일', '뷰티풀 군바리', '설이')

